In [1]:
import pandas as pd
import numpy as np

In [3]:
import os
print(os.getcwd())

c:\Users\user\Desktop\Supplement-Sales-Intelligence-Dashboard\notebooks

In [4]:
df = pd.read_csv("../data/raw/supplement_sales.csv")

df.head()

,Order_ID,Order_Date,Customer_ID,Age,Gender,State,Product_Name,Category,Quantity,Unit_Price,Revenue,Payment_Method,Channel,Customer_Type
0,ORD00001,2024-09-27,CUST6191,38,Male,Haryana,Immunity Booster,Immunity,4,649,2596,Debit Card,Flipkart,New
1,ORD00002,2025-10-25,CUST9322,39,Male,Maharashtra,Weight Control Capsules,Weight Management,4,1199,4796,COD,Amazon,New
2,ORD00003,2024-06-09,CUST5555,39,Male,Punjab,Detox Tea,Detox,5,599,2995,UPI,Flipkart,Repeat
3,ORD00004,2025-11-30,CUST1189,20,Male,Karnataka,Hair Serum,Hair Care,4,699,2796,Debit Card,Website,Repeat
4,ORD00005,2025-08-23,CUST9433,26,Female,Bihar,Hair Serum,Hair Care,4,699,2796,Credit Card,Flipkart,Repeat

In [5]:
df.shape

(10000, 14)

In [6]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Age', 'Gender', 'State',
       'Product_Name', 'Category', 'Quantity', 'Unit_Price', 'Revenue',
       'Payment_Method', 'Channel', 'Customer_Type'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        10000 non-null  str
 1   Order_Date      10000 non-null  str
 2   Customer_ID     10000 non-null  str
 3   Age             10000 non-null  int64
 4   Gender          10000 non-null  str
 5   State           10000 non-null  str
 6   Product_Name    10000 non-null  str
 7   Category        10000 non-null  str
 8   Quantity        10000 non-null  int64
 9   Unit_Price      10000 non-null  int64
 10  Revenue         10000 non-null  int64
 11  Payment_Method  10000 non-null  str
 12  Channel         10000 non-null  str
 13  Customer_Type   10000 non-null  str
dtypes: int64(4), str(10)
memory usage: 1.1 MB

In [8]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_ID       0
Age               0
Gender            0
State             0
Product_Name      0
Category          0
Quantity          0
Unit_Price        0
Revenue           0
Payment_Method    0
Channel           0
Customer_Type     0
dtype: int64

In [9]:
df.describe()

                Age      Quantity    Unit_Price       Revenue
count  10000.000000  10000.000000  10000.000000  10000.000000
mean      38.624000      2.996400    766.685000   2293.838600
std       12.172602      1.416682    216.606054   1296.288216
min       18.000000      1.000000    499.000000    499.000000
25%       28.000000      2.000000    599.000000   1199.000000
50%       39.000000      3.000000    699.000000   2097.000000
75%       49.000000      4.000000    899.000000   3196.000000
max       59.000000      5.000000   1199.000000   5995.000000